config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'dreams#index', as: 'dreams_index'
  get '/search_dreams', to: 'dreams#search_dreams', as: 'search_dreams'
  get '/display_dream', to: 'dreams#display_dream', as: 'display_dream'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dream.rb
class Dream < ActiveRecord::Base
  self.table_name = 'dream'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  protect_from_forgery except: :search_dreams
  def index
    dream_count = Dream.count()
    dream_id = rand(1..dream_count)
    @dream = Dream.find(dream_id)
  end

  def search_dreams
    @dreams = Dream.limit(1000).where('content LIKE ?', "%#{params[:text]}%")
    render json: { html: render_to_string(partial: 'search_results', locals: { query: params[:text] }) }
  end

  def display_dream
    @dream = Dream.find(params[:id])
    @dream.content.gsub!(/\b(#{params[:selected]})\b/i, '<span class="dream__search--prev">\1</span>')
    render json: { html: render_to_string(partial: 'dream') }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/views/dreams/_dream.html.erb
  <div class="dream">

    <h1><%=@dream.title%></h1>
    <h3><%=@dream.collection%></h3>
    <div>----------------------------------------------------------------------</div>
    <p class="dream-text"><%=@dream.content.html_safe%></p>
  </div>

app/views/dreams/_search_results.html.erb
<div class="search-results">
  <h3>Results for <span class="search-results__query">"<%= query %>"</span></h3>
  <ul class="search-results__list">
    <% @dreams.each do |dream|  %>
      <li class="search-results__item"><%= link_to dream.title, display_dream_path(id: dream.id, selected: query), remote:true, data: {trigger: 'display_dream'}, class: "search-results__link"%></li>
    <%end%>
  </ul>
</div>

app/views/dreams/index.html.erb
<div class="modal hidden" id="modal">
  <div class="modal__container">
    <h1>What is this?</h1>
    <p>Dreamscape is a freeform way to explore the huge list of dreams provided at <a href="https://www.dreambank.net/">Dreambank</a>. The Dreambank UI is very functional but doesn't give you a way to easily explore the links and relationships between different dreams.</p>
    <p>
      With Dreamscape you are first presented with a random dream from the database. Highlighting a word or phrase will bring up a list of all other dreams that contain the highlighted text, clicking on a dream will open it. You can continue this process indefinitely to build a retraceable path through the dream database.
    </p>
    <p>
      I am still ironing out some kinks and working on improving the search functionality.
    </p>
    <a id="close-modal" class="modal__close-button">close</a>
  </div>
</div>
<header class="header">
  <a class="header__modal-link" id="modal-link">?</a>
  <h1 class="header__site-heading">Dreamscape</h1>
  <%# <a class="header__randomize-button">Randomize</a> %>
  <%= link_to "Randomize", dreams_index_path, class: "header__randomize-button"  %>
  <p class="header__instructions">Highlight a word or phrase to search the databse.</p>

</header>
<div id="main" class="main">
  <%= render 'dream' %>
</div>

<%= javascript_pack_tag 'toggle_modal' %>
<%= javascript_pack_tag 'highlight_search' %>
<%= javascript_pack_tag 'display_dream' %>
<%= javascript_pack_tag 'highlight_selected_dream_result' %>

app/views/dreams/old.display_dream.js.erb
document.getElementById('main')
  .insertAdjacentHTML("beforeend", "<%= j render('dream') %>");

app/views/dreams/old.search_dreams.js.erb
document.getElementById('main')
  .insertAdjacentHTML("beforeend", "<%= j render('search_results') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dreamscrape</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>